#[derive(Clone, Copy, Debug)]
struct ToolRuntimeKillManifest {
    commands: &'static [&'static str],
    windows_process_names: &'static [&'static str],
    macos_process_names: &'static [&'static str],
    linux_process_names: &'static [&'static str],
    extension_dir_prefixes: &'static [&'static str],
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum ToolCommandLaunch {
    Disabled,
    Terminal,
    Desktop,
}

#[derive(Clone, Copy, Debug)]
struct ToolProfile {
    id: &'static str,
    display_name: &'static str,
    protocols: &'static [ToolProtocol],
    default_protocol: ToolProtocol,
    model_sync_policy: ToolModelSyncPolicy,
    runtime: ToolRuntimeKillManifest,
    command_launch: ToolCommandLaunch,
    launch_args: &'static [&'static str],
    desktop_preferred: bool,
    identity_aliases: &'static [&'static str],
    external_environment_names: &'static [&'static str],
    #[cfg_attr(not(target_os = "macos"), allow(dead_code))]
    macos_app_names: &'static [&'static str],
    #[cfg_attr(not(target_os = "windows"), allow(dead_code))]
    windows_program_paths: &'static [(&'static str, &'static str)],
}

const fn runtime_command_manifest(commands: &'static [&'static str]) -> ToolRuntimeKillManifest {
    ToolRuntimeKillManifest {
        commands,
        windows_process_names: &[],
        macos_process_names: &[],
        linux_process_names: &[],
        extension_dir_prefixes: &[],
    }
}

const fn desktop_and_command_manifest(
    commands: &'static [&'static str],
    windows_process_names: &'static [&'static str],
    macos_process_names: &'static [&'static str],
    linux_process_names: &'static [&'static str],
) -> ToolRuntimeKillManifest {
    ToolRuntimeKillManifest {
        commands,
        windows_process_names,
        macos_process_names,
        linux_process_names,
        extension_dir_prefixes: &[],
    }
}

// Stable tool traits live here so protocol selection, model synchronization,
// discovery, process ownership and launch all agree. Tool-specific config
// readers/writers and dynamic package discovery remain in their own modules.
const TOOL_PROFILES: &[ToolProfile] = &[
    ToolProfile {
        id: "grok-build",
        display_name: "Grok Build",
        protocols: &[
            ToolProtocol::OpenAiResponses,
            ToolProtocol::AnthropicMessages,
            ToolProtocol::OpenAiChat,
        ],
        default_protocol: ToolProtocol::OpenAiResponses,
        model_sync_policy: ToolModelSyncPolicy::Catalog,
        runtime: runtime_command_manifest(&["grok"]),
        command_launch: ToolCommandLaunch::Terminal,
        launch_args: &[],
        desktop_preferred: false,
        identity_aliases: &[],
        external_environment_names: &[],
        macos_app_names: &[],
        windows_program_paths: &[],
    },
    ToolProfile {
        id: "minimax-code",
        display_name: "MiniMax Code",
        protocols: &[
            ToolProtocol::AnthropicMessages,
            ToolProtocol::OpenAiResponses,
            ToolProtocol::OpenAiChat,
        ],
        default_protocol: ToolProtocol::AnthropicMessages,
        model_sync_policy: ToolModelSyncPolicy::Catalog,
        // Desktop and CLI both read ~/.minimax/config.yaml (MINIMAX_DATA_DIR override).
        runtime: desktop_and_command_manifest(
            &["mcode"],
            &["MiniMax Code.exe"],
            &["MiniMax Code", "mcode"],
            &["minimax-code", "mcode"],
        ),
        command_launch: ToolCommandLaunch::Terminal,
        launch_args: &[],
        desktop_preferred: true,
        identity_aliases: &[],
        external_environment_names: &[],
        macos_app_names: &["MiniMax Code.app"],
        windows_program_paths: &[("MiniMax Code", "MiniMax Code.exe")],
    },
    ToolProfile {
        id: "codex",
        display_name: "Codex",
        protocols: &[ToolProtocol::OpenAiResponses],
        default_protocol: ToolProtocol::OpenAiResponses,
        model_sync_policy: ToolModelSyncPolicy::None,
        runtime: ToolRuntimeKillManifest {
            commands: &["codex"],
            windows_process_names: &["ChatGPT.exe", "chatgpt.exe", "Codex.exe", "codex.exe"],
            macos_process_names: &["ChatGPT", "Codex", "codex"],
            linux_process_names: &["chatgpt", "codex"],
            extension_dir_prefixes: &["openai.chatgpt-", "openai.codex-"],
        },
        command_launch: ToolCommandLaunch::Disabled,
        launch_args: &[],
        desktop_preferred: true,
        identity_aliases: &[],
        external_environment_names: &[],
        macos_app_names: &["ChatGPT.app", "Codex.app"],
        windows_program_paths: &[
            ("ChatGPT", "ChatGPT.exe"),
            ("OpenAI ChatGPT", "ChatGPT.exe"),
            ("Codex", "Codex.exe"),
            ("OpenAI Codex", "Codex.exe"),
        ],
    },
    ToolProfile {
        id: "claude",
        display_name: "Claude Code",
        protocols: &[ToolProtocol::AnthropicMessages],
        default_protocol: ToolProtocol::AnthropicMessages,
        model_sync_policy: ToolModelSyncPolicy::None,
        runtime: ToolRuntimeKillManifest {
            commands: &["claude"],
            windows_process_names: &["claude.exe"],
            macos_process_names: &["claude"],
            linux_process_names: &["claude"],
            extension_dir_prefixes: &["anthropic.claude-code-"],
        },
        command_launch: ToolCommandLaunch::Terminal,
        launch_args: &[],
        desktop_preferred: false,
        identity_aliases: &[],
        external_environment_names: CLAUDE_CODE_EXTERNAL_ENVIRONMENT_NAMES,
        macos_app_names: &[],
        windows_program_paths: &[],
    },
    ToolProfile {
        id: "claude-desktop",
        display_name: "Claude Desktop",
        protocols: &[ToolProtocol::AnthropicMessages],
        default_protocol: ToolProtocol::AnthropicMessages,
        model_sync_policy: ToolModelSyncPolicy::Catalog,
        runtime: ToolRuntimeKillManifest {
            commands: &[],
            windows_process_names: &["Claude.exe"],
            macos_process_names: &["Claude"],
            linux_process_names: &["claude-desktop"],
            extension_dir_prefixes: &[],
        },
        command_launch: ToolCommandLaunch::Terminal,
        launch_args: &[],
        desktop_preferred: true,
        identity_aliases: &[],
        external_environment_names: &[],
        macos_app_names: &["Claude.app"],
        windows_program_paths: &[("Claude", "Claude.exe"), ("AnthropicClaude", "Claude.exe")],
    },
    ToolProfile {
        id: "claude-science",
        display_name: "Claude Science",
        protocols: &[ToolProtocol::AnthropicMessages],
        default_protocol: ToolProtocol::AnthropicMessages,
        model_sync_policy: ToolModelSyncPolicy::None,
        runtime: runtime_command_manifest(&["claude-science"]),
        command_launch: ToolCommandLaunch::Terminal,
        launch_args: &["serve"],
        desktop_preferred: false,
        identity_aliases: &[],
        external_environment_names: CLAUDE_SCIENCE_EXTERNAL_ENVIRONMENT_NAMES,
        macos_app_names: &[],
        windows_program_paths: &[("ClaudeScience", "claude-science.exe")],
    },
    ToolProfile {
        id: "gemini",
        display_name: "Gemini CLI",
        protocols: &[ToolProtocol::GeminiNative],
        default_protocol: ToolProtocol::GeminiNative,
        model_sync_policy: ToolModelSyncPolicy::None,
        runtime: ToolRuntimeKillManifest {
            commands: &["gemini"],
            windows_process_names: &["gemini.exe"],
            macos_process_names: &["gemini"],
            linux_process_names: &["gemini"],
            extension_dir_prefixes: &["google.gemini-cli-vscode-ide-companion-"],
        },
        command_launch: ToolCommandLaunch::Terminal,
        launch_args: &[],
        desktop_preferred: false,
        identity_aliases: &[],
        external_environment_names: GEMINI_CLI_EXTERNAL_ENVIRONMENT_NAMES,
        macos_app_names: &[],
        windows_program_paths: &[],
    },
    ToolProfile {
        id: "copilot",
        display_name: "GitHub Copilot CLI",
        protocols: &[ToolProtocol::OpenAiChat],
        default_protocol: ToolProtocol::OpenAiChat,
        model_sync_policy: ToolModelSyncPolicy::Selected,
        runtime: runtime_command_manifest(&["copilot"]),
        command_launch: ToolCommandLaunch::Terminal,
        launch_args: &[],
        desktop_preferred: false,
        identity_aliases: &[],
        external_environment_names: &[],
        macos_app_names: &[],
        windows_program_paths: &[],
    },
    ToolProfile {
        id: "copilot-desktop",
        display_name: "GitHub Copilot",
        protocols: &[
            ToolProtocol::OpenAiResponses,
            ToolProtocol::OpenAiChat,
            ToolProtocol::AnthropicMessages,
        ],
        default_protocol: ToolProtocol::OpenAiResponses,
        model_sync_policy: ToolModelSyncPolicy::Catalog,
        runtime: desktop_and_command_manifest(
            &[],
            &["github.exe"],
            &["GitHub Copilot", "github"],
            &[],
        ),
        command_launch: ToolCommandLaunch::Disabled,
        launch_args: &[],
        desktop_preferred: true,
        identity_aliases: &["githubcopilot"],
        external_environment_names: &[],
        macos_app_names: &["GitHub Copilot.app"],
        windows_program_paths: &[("GitHub Copilot", "github.exe")],
    },
    ToolProfile {
        id: "cline",
        display_name: "Cline",
        protocols: &[ToolProtocol::OpenAiResponses, ToolProtocol::OpenAiChat],
        default_protocol: ToolProtocol::OpenAiResponses,
        model_sync_policy: ToolModelSyncPolicy::Catalog,
        runtime: ToolRuntimeKillManifest {
            commands: &["cline"],
            windows_process_names: &["cline-app.exe", "cline.exe"],
            macos_process_names: &["cline-app", "Cline", "Cline Beta", "cline"],
            linux_process_names: &["cline-app", "cline"],
            extension_dir_prefixes: &["saoudrizwan.claude-dev-"],
        },
        command_launch: ToolCommandLaunch::Terminal,
        launch_args: &[],
        desktop_preferred: true,
        identity_aliases: &[],
        external_environment_names: &[],
        macos_app_names: &["Cline.app", "Cline Beta.app"],
        windows_program_paths: &[("Cline", "cline-app.exe"), ("Cline Beta", "cline-app.exe")],
    },
    ToolProfile {
        id: "trae",
        display_name: "TraeCode",
        protocols: &[
            ToolProtocol::OpenAiChat,
            ToolProtocol::OpenAiResponses,
            ToolProtocol::AnthropicMessages,
        ],
        default_protocol: ToolProtocol::OpenAiChat,
        model_sync_policy: ToolModelSyncPolicy::Catalog,
        runtime: desktop_and_command_manifest(&[], &["Trae.exe"], &["Trae"], &["trae"]),
        command_launch: ToolCommandLaunch::Disabled,
        launch_args: &[],
        desktop_preferred: true,
        identity_aliases: &["traecode"],
        external_environment_names: &[],
        macos_app_names: &["Trae.app"],
        windows_program_paths: &[("Trae", "Trae.exe")],
    },
    ToolProfile {
        id: "trae-cn",
        display_name: "TraeCode CN",
        protocols: &[
            ToolProtocol::OpenAiChat,
            ToolProtocol::OpenAiResponses,
            ToolProtocol::AnthropicMessages,
        ],
        default_protocol: ToolProtocol::OpenAiChat,
        model_sync_policy: ToolModelSyncPolicy::Catalog,
        runtime: desktop_and_command_manifest(&[], &["Trae CN.exe"], &["Trae CN"], &["trae-cn"]),
        command_launch: ToolCommandLaunch::Disabled,
        launch_args: &[],
        desktop_preferred: true,
        identity_aliases: &["traecodecn"],
        external_environment_names: &[],
        macos_app_names: &["Trae CN.app"],
        windows_program_paths: &[("Trae CN", "Trae CN.exe")],
    },
    ToolProfile {
        id: "trae-work",
        display_name: "TraeWork",
        protocols: &[
            ToolProtocol::OpenAiChat,
            ToolProtocol::OpenAiResponses,
            ToolProtocol::AnthropicMessages,
        ],
        default_protocol: ToolProtocol::OpenAiChat,
        model_sync_policy: ToolModelSyncPolicy::Catalog,
        runtime: desktop_and_command_manifest(
            &[],
            &["TRAE SOLO CN.exe", "TraeWork CN.exe"],
            &["TRAE SOLO CN", "TraeWork CN"],
            &[],
        ),
        command_launch: ToolCommandLaunch::Disabled,
        launch_args: &[],
        desktop_preferred: true,
        identity_aliases: &["traework", "trae-solo-cn"],
        external_environment_names: &[],
        macos_app_names: &["TRAE SOLO CN.app", "TraeWork CN.app"],
        windows_program_paths: &[
            ("TRAE SOLO CN", "TRAE SOLO CN.exe"),
            ("TraeWork CN", "TraeWork CN.exe"),
        ],
    },
    ToolProfile {
        id: "opencode",
        display_name: "OpenCode",
        protocols: &[
            ToolProtocol::OpenAiResponses,
            ToolProtocol::AnthropicMessages,
            ToolProtocol::GeminiNative,
            ToolProtocol::OpenAiChat,
        ],
        default_protocol: ToolProtocol::OpenAiResponses,
        model_sync_policy: ToolModelSyncPolicy::Catalog,
        runtime: desktop_and_command_manifest(
            &["opencode"],
            &["OpenCode.exe", "OpenCode Beta.exe", "opencode.exe"],
            &["OpenCode", "OpenCode Beta", "opencode"],
            &["opencode"],
        ),
        command_launch: ToolCommandLaunch::Terminal,
        launch_args: &[],
        desktop_preferred: true,
        identity_aliases: &[],
        external_environment_names: &["OPENCODE_CONFIG_CONTENT"],
        macos_app_names: &["OpenCode.app"],
        windows_program_paths: &[
            ("OpenCode", "OpenCode.exe"),
            ("opencode", "OpenCode.exe"),
            ("@opencode-aidesktop", "OpenCode.exe"),
            ("OpenCode Beta", "OpenCode Beta.exe"),
        ],
    },
    ToolProfile {
        id: "openclaw",
        display_name: "OpenClaw",
        protocols: &[
            ToolProtocol::OpenAiResponses,
            ToolProtocol::OpenAiChat,
            ToolProtocol::AnthropicMessages,
            ToolProtocol::GeminiNative,
        ],
        default_protocol: ToolProtocol::OpenAiResponses,
        model_sync_policy: ToolModelSyncPolicy::Catalog,
        runtime: desktop_and_command_manifest(
            &["openclaw"],
            &["OpenClaw.exe", "openclaw.exe"],
            &["OpenClaw", "openclaw"],
            &["openclaw"],
        ),
        command_launch: ToolCommandLaunch::Terminal,
        launch_args: &[],
        desktop_preferred: true,
        identity_aliases: &[],
        external_environment_names: &[],
        macos_app_names: &["OpenClaw.app"],
        windows_program_paths: &[("OpenClaw", "OpenClaw.exe")],
    },
    ToolProfile {
        id: "goose",
        display_name: "Goose",
        protocols: &[ToolProtocol::OpenAiChat],
        default_protocol: ToolProtocol::OpenAiChat,
        model_sync_policy: ToolModelSyncPolicy::Catalog,
        runtime: desktop_and_command_manifest(
            &["goose"],
            &["Goose.exe", "goose.exe"],
            &["Goose", "goose"],
            &["goose"],
        ),
        command_launch: ToolCommandLaunch::Terminal,
        launch_args: &[],
        desktop_preferred: true,
        identity_aliases: &[],
        external_environment_names: &[],
        macos_app_names: &["Goose.app"],
        windows_program_paths: &[("Goose", "Goose.exe"), ("goose", "Goose.exe")],
    },
    ToolProfile {
        id: "raven",
        display_name: "Raven",
        protocols: &[ToolProtocol::OpenAiChat],
        default_protocol: ToolProtocol::OpenAiChat,
        model_sync_policy: ToolModelSyncPolicy::Catalog,
        runtime: runtime_command_manifest(&["raven"]),
        command_launch: ToolCommandLaunch::Terminal,
        launch_args: &[],
        desktop_preferred: false,
        identity_aliases: &[],
        external_environment_names: &[],
        macos_app_names: &[],
        windows_program_paths: &[],
    },
    ToolProfile {
        id: "reasonix",
        display_name: "DeepSeek Reasonix",
        protocols: &[ToolProtocol::OpenAiChat],
        default_protocol: ToolProtocol::OpenAiChat,
        model_sync_policy: ToolModelSyncPolicy::Catalog,
        runtime: desktop_and_command_manifest(
            &["reasonix"],
            &["Reasonix.exe", "reasonix.exe"],
            &["Reasonix", "reasonix"],
            &["reasonix", "reasonix-desktop", "reasonix-launcher"],
        ),
        command_launch: ToolCommandLaunch::Terminal,
        launch_args: &[],
        desktop_preferred: true,
        identity_aliases: &["DeepSeek Reasonix"],
        external_environment_names: &[],
        macos_app_names: &["Reasonix.app"],
        windows_program_paths: &[
            ("Reasonix", "Reasonix.exe"),
            ("DeepSeek Reasonix", "Reasonix.exe"),
        ],
    },
    ToolProfile {
        id: "deepseek-harness",
        display_name: "DeepSeek Harness",
        protocols: &[
            ToolProtocol::OpenAiChat,
            ToolProtocol::OpenAiResponses,
            ToolProtocol::AnthropicMessages,
        ],
        default_protocol: ToolProtocol::OpenAiChat,
        model_sync_policy: ToolModelSyncPolicy::Catalog,
        runtime: desktop_and_command_manifest(
            &["dsh"],
            &["DeepSeek Harness.exe", "dsh.exe"],
            &["DeepSeek Harness", "dsh"],
            &["dsh"],
        ),
        command_launch: ToolCommandLaunch::Terminal,
        launch_args: &["web"],
        desktop_preferred: true,
        identity_aliases: &[],
        external_environment_names: &[],
        macos_app_names: &["DeepSeek Harness.app"],
        windows_program_paths: &[("DeepSeek Harness", "DeepSeek Harness.exe")],
    },
    ToolProfile {
        id: "pi",
        display_name: "Pi",
        protocols: &[
            ToolProtocol::OpenAiResponses,
            ToolProtocol::AnthropicMessages,
            ToolProtocol::GeminiNative,
            ToolProtocol::OpenAiChat,
        ],
        default_protocol: ToolProtocol::OpenAiResponses,
        model_sync_policy: ToolModelSyncPolicy::Catalog,
        runtime: runtime_command_manifest(&["pi"]),
        command_launch: ToolCommandLaunch::Terminal,
        launch_args: &[],
        desktop_preferred: false,
        identity_aliases: &[],
        external_environment_names: &[],
        macos_app_names: &[],
        windows_program_paths: &[],
    },
    ToolProfile {
        id: "hermes",
        display_name: "Hermes",
        protocols: &[ToolProtocol::OpenAiChat],
        default_protocol: ToolProtocol::OpenAiChat,
        model_sync_policy: ToolModelSyncPolicy::None,
        runtime: desktop_and_command_manifest(
            &["hermes"],
            &["Hermes.exe", "hermes.exe"],
            &["Hermes", "hermes"],
            &["hermes"],
        ),
        command_launch: ToolCommandLaunch::Terminal,
        launch_args: &[],
        desktop_preferred: true,
        identity_aliases: &["Hermes Agent"],
        external_environment_names: &[],
        macos_app_names: &["Hermes Agent.app", "Hermes.app"],
        windows_program_paths: &[],
    },
    ToolProfile {
        id: "vscode",
        display_name: "VS Code",
        protocols: &[
            ToolProtocol::OpenAiResponses,
            ToolProtocol::OpenAiChat,
            ToolProtocol::AnthropicMessages,
        ],
        default_protocol: ToolProtocol::OpenAiResponses,
        model_sync_policy: ToolModelSyncPolicy::Catalog,
        runtime: desktop_and_command_manifest(&["code"], &["Code.exe"], &["Code"], &["code"]),
        command_launch: ToolCommandLaunch::Desktop,
        launch_args: &[],
        desktop_preferred: true,
        identity_aliases: &["Visual Studio Code"],
        external_environment_names: &[],
        macos_app_names: &["Visual Studio Code.app"],
        windows_program_paths: &[("Microsoft VS Code", "Code.exe")],
    },
    ToolProfile {
        id: "workbuddy",
        display_name: "WorkBuddy",
        protocols: &[ToolProtocol::OpenAiChat],
        default_protocol: ToolProtocol::OpenAiChat,
        model_sync_policy: ToolModelSyncPolicy::Catalog,
        runtime: desktop_and_command_manifest(
            &["workbuddy"],
            &["WorkBuddy.exe"],
            &["WorkBuddy", "workbuddy"],
            &["workbuddy"],
        ),
        command_launch: ToolCommandLaunch::Desktop,
        launch_args: &[],
        desktop_preferred: true,
        identity_aliases: &[],
        external_environment_names: &[],
        macos_app_names: &["WorkBuddy.app"],
        windows_program_paths: &[("WorkBuddy", "WorkBuddy.exe")],
    },
    ToolProfile {
        id: "kimicode",
        display_name: "Kimi Code",
        protocols: &[ToolProtocol::OpenAiResponses, ToolProtocol::OpenAiChat],
        default_protocol: ToolProtocol::OpenAiResponses,
        model_sync_policy: ToolModelSyncPolicy::Catalog,
        runtime: desktop_and_command_manifest(
            &["kimi"],
            &["Kimi Code.exe"],
            &["Kimi Code", "kimi"],
            &["kimi"],
        ),
        command_launch: ToolCommandLaunch::Terminal,
        launch_args: &[],
        desktop_preferred: true,
        identity_aliases: &["kimi-code-app"],
        external_environment_names: &[],
        macos_app_names: &["Kimi Code.app"],
        windows_program_paths: &[
            ("kimi-code-app", "Kimi Code.exe"),
            ("Kimi Code", "Kimi Code.exe"),
        ],
    },
    ToolProfile {
        id: "mimocode",
        display_name: "MiMo Code",
        protocols: &[
            ToolProtocol::OpenAiChat,
            ToolProtocol::OpenAiResponses,
            ToolProtocol::AnthropicMessages,
            ToolProtocol::GeminiNative,
        ],
        default_protocol: ToolProtocol::OpenAiChat,
        model_sync_policy: ToolModelSyncPolicy::Catalog,
        // Xiaomi MiMo desktop reads the same MIMOCODE_HOME/config catalog.
        runtime: desktop_and_command_manifest(
            &["mimo"],
            &["Xiaomi MiMo.exe", "Xiaomi MiMo AI.exe"],
            &["Xiaomi MiMo", "Xiaomi MiMo AI", "mimo"],
            &["mimo"],
        ),
        command_launch: ToolCommandLaunch::Terminal,
        launch_args: &[],
        desktop_preferred: true,
        identity_aliases: &[],
        external_environment_names: &[],
        macos_app_names: &["Xiaomi MiMo.app", "Xiaomi MiMo AI.app"],
        windows_program_paths: &[
            ("Xiaomi MiMo", "Xiaomi MiMo.exe"),
            ("Xiaomi MiMo AI", "Xiaomi MiMo AI.exe"),
        ],
    },
    ToolProfile {
        id: "qwencode",
        display_name: "Qwen Code",
        protocols: &[ToolProtocol::OpenAiChat],
        default_protocol: ToolProtocol::OpenAiChat,
        model_sync_policy: ToolModelSyncPolicy::Catalog,
        runtime: desktop_and_command_manifest(
            &["qwen"],
            &["qwen-code-desktop.exe", "Qwen Code Desktop.exe"],
            &["qwen-code-desktop", "Qwen Code Desktop", "qwen"],
            &["qwen-code-desktop", "qwen"],
        ),
        command_launch: ToolCommandLaunch::Terminal,
        launch_args: &[],
        desktop_preferred: true,
        identity_aliases: &["Qwen Code Desktop"],
        external_environment_names: &[],
        macos_app_names: &["Qwen Code Desktop.app"],
        windows_program_paths: &[
            ("Qwen Code Desktop", "qwen-code-desktop.exe"),
            ("Qwen Code Desktop", "Qwen Code Desktop.exe"),
            ("qwen-code-desktop", "qwen-code-desktop.exe"),
            ("qwen-code-desktop", "Qwen Code Desktop.exe"),
        ],
    },
    ToolProfile {
        id: "openscience",
        display_name: "Open Science",
        protocols: &[ToolProtocol::OpenAiChat, ToolProtocol::OpenAiResponses],
        default_protocol: ToolProtocol::OpenAiChat,
        model_sync_policy: ToolModelSyncPolicy::Catalog,
        runtime: desktop_and_command_manifest(
            &[],
            &["ai4s-workbench.exe"],
            &["ai4s-workbench"],
            &["ai4s-workbench"],
        ),
        command_launch: ToolCommandLaunch::Disabled,
        launch_args: &[],
        desktop_preferred: true,
        identity_aliases: &["Open Science"],
        external_environment_names: &[],
        macos_app_names: &["Open Science.app"],
        windows_program_paths: &[("Open Science", "ai4s-workbench.exe")],
    },
    ToolProfile {
        id: "open-interpreter",
        display_name: "Open Interpreter",
        protocols: &[ToolProtocol::OpenAiChat],
        default_protocol: ToolProtocol::OpenAiChat,
        model_sync_policy: ToolModelSyncPolicy::Selected,
        runtime: runtime_command_manifest(&["interpreter"]),
        command_launch: ToolCommandLaunch::Terminal,
        launch_args: &[],
        desktop_preferred: false,
        identity_aliases: &[],
        external_environment_names: &[],
        macos_app_names: &[],
        windows_program_paths: &[],
    },
    ToolProfile {
        id: "anythingllm",
        display_name: "AnythingLLM",
        protocols: &[ToolProtocol::OpenAiChat],
        default_protocol: ToolProtocol::OpenAiChat,
        model_sync_policy: ToolModelSyncPolicy::Selected,
        runtime: desktop_and_command_manifest(
            &["anythingllm-desktop", "anythingllm"],
            &["AnythingLLM.exe"],
            &["AnythingLLM"],
            &["anythingllm-desktop", "anythingllm"],
        ),
        command_launch: ToolCommandLaunch::Desktop,
        launch_args: &[],
        desktop_preferred: true,
        identity_aliases: &["anythingllm-desktop", "AnythingLLMDesktop.AppImage"],
        external_environment_names: &[],
        macos_app_names: &["AnythingLLM.app"],
        windows_program_paths: &[
            ("AnythingLLM", "AnythingLLM.exe"),
            ("anythingllm-desktop", "AnythingLLM.exe"),
        ],
    },
    ToolProfile {
        id: "mistral-vibe",
        display_name: "Mistral Vibe",
        protocols: &[ToolProtocol::OpenAiChat],
        default_protocol: ToolProtocol::OpenAiChat,
        model_sync_policy: ToolModelSyncPolicy::Catalog,
        runtime: runtime_command_manifest(&["vibe"]),
        command_launch: ToolCommandLaunch::Terminal,
        launch_args: &[],
        desktop_preferred: false,
        identity_aliases: &[],
        external_environment_names: &[],
        macos_app_names: &[],
        windows_program_paths: &[],
    },
    ToolProfile {
        id: "open-design",
        display_name: "Open Design",
        protocols: &[ToolProtocol::OpenAiResponses],
        default_protocol: ToolProtocol::OpenAiResponses,
        model_sync_policy: ToolModelSyncPolicy::Selected,
        runtime: ToolRuntimeKillManifest {
            commands: &["od"],
            windows_process_names: &[
                "Open Design.exe",
                "Open Design Beta.exe",
                "Open Design Prerelease.exe",
                "Open Design Preview.exe",
                "od.exe",
            ],
            macos_process_names: &[
                "Open Design",
                "Open Design Beta",
                "Open Design Prerelease",
                "Open Design Preview",
                "od",
            ],
            linux_process_names: &["od"],
            extension_dir_prefixes: &[],
        },
        command_launch: ToolCommandLaunch::Terminal,
        launch_args: &[],
        desktop_preferred: true,
        identity_aliases: &[],
        external_environment_names: &[],
        macos_app_names: &[
            "Open Design.app",
            "Open Design Beta.app",
            "Open Design Prerelease.app",
            "Open Design Preview.app",
        ],
        windows_program_paths: &[
            ("Open Design", "Open Design.exe"),
            ("Open Design Beta", "Open Design Beta.exe"),
            ("Open Design Prerelease", "Open Design Prerelease.exe"),
            ("Open Design Preview", "Open Design Preview.exe"),
        ],
    },
    ToolProfile {
        id: "vibe-trading",
        display_name: "Vibe-Trading",
        protocols: &[ToolProtocol::OpenAiChat],
        default_protocol: ToolProtocol::OpenAiChat,
        model_sync_policy: ToolModelSyncPolicy::Selected,
        runtime: runtime_command_manifest(&["vibe-trading"]),
        command_launch: ToolCommandLaunch::Terminal,
        launch_args: &[],
        desktop_preferred: false,
        identity_aliases: &[],
        external_environment_names: &[],
        macos_app_names: &[],
        windows_program_paths: &[],
    },
    ToolProfile {
        id: "zcode",
        display_name: "ZCode",
        protocols: &[ToolProtocol::OpenAiChat],
        default_protocol: ToolProtocol::OpenAiChat,
        model_sync_policy: ToolModelSyncPolicy::Catalog,
        runtime: ToolRuntimeKillManifest {
            commands: &[],
            windows_process_names: &["ZCode.exe"],
            macos_process_names: &["ZCode"],
            linux_process_names: &["zcode"],
            extension_dir_prefixes: &[],
        },
        command_launch: ToolCommandLaunch::Terminal,
        launch_args: &[],
        desktop_preferred: true,
        identity_aliases: &[],
        external_environment_names: &[],
        macos_app_names: &["ZCode.app"],
        windows_program_paths: &[("ZCode", "ZCode.exe")],
    },
];

fn tool_profile(tool: &str) -> Option<&'static ToolProfile> {
    TOOL_PROFILES.iter().find(|profile| profile.id == tool)
}

pub(crate) fn tool_model_sync_policy(tool: &str) -> ToolModelSyncPolicy {
    tool_profile(tool)
        .map(|profile| profile.model_sync_policy)
        .unwrap_or(ToolModelSyncPolicy::None)
}

fn tool_runtime_display_name(tool: &str) -> &str {
    tool_profile(tool)
        .map(|profile| profile.display_name)
        .unwrap_or(tool)
}

fn tool_runtime_kill_manifest(tool: &str) -> Option<ToolRuntimeKillManifest> {
    tool_profile(tool).map(|profile| profile.runtime)
}
